 const transactions = [
  {
    id: 1,
    title: "Gaji Bulanan",
    amount: 5000000,
    category: "Salary",
    date: "1 Jan 2026",
    income: true,
  },
  {
    id: 2,
    title: "Makan Siang",
    amount: 25000,
    category: "Food",
    date: "3 Jan 2026",
    income: false,
  },
  {
    id: 3,
    title: "Freelance Project",
    amount: 750000,
    category: "Project",
    date: "5 Jan 2026",
    income: true,
  },
  {
    id: 4,
    title: "Transport Ojek",
    amount: 18000,
    category: "Transport",
    date: "6 Jan 2026",
    income: false,
  },
  {
    id: 5,
    title: "Beli Kopi",
    amount: 20000,
    category: "Food",
    date: "7 Jan 2026",
    income: false,
  },
  {
    id: 6,
    title: "Bonus Kantor",
    amount: 1000000,
    category: "Bonus",
    date: "10 Jan 2026",
    income: true,
  },
  {
    id: 7,
    title: "Langganan Netflix",
    amount: 65000,
    category: "Subscription",
    date: "12 Jan 2026",
    income: false,
  },
  {
    id: 8,
    title: "Jual Barang Bekas",
    amount: 300000,
    category: "Other Income",
    date: "15 Jan 2026",
    income: true,
  },
  {
    id: 9,
    title: "Belanja Bulanan",
    amount: 450000,
    category: "Groceries",
    date: "18 Jan 2026",
    income: false,
  },
  {
    id: 10,
    title: "Bayar Internet",
    amount: 350000,
    category: "Utilities",
    date: "20 Jan 2026",
    income: false,
  },
]

export default transactions
